import "./globals.css";
import { Space_Grotesk } from "next/font/google";

const inter = Space_Grotesk({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by Emre Ates",
  icons: {
    icon: "favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} overflow-x-hidden bg-white text-black dark:bg-black dark:text-white`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
